---
title: "Module 3 Output"
author: "Gian Carlo Fernandez"
date: "7/23/2021"
output: 
  html_document:
    highlight: pygments
    theme: darkly
---
# Individual Quiz {.tabset}

## Question 1


### The life in hours of a battery is known to be approximately normally distributed with standard deviation σ=1.25 hours. A random sample of 10 batteries has a mean life of x̄= 40.5 hours. 
<br>

#### Is there evidence to support the claim that battery life exceeds 40 hours? Use α=0.05.
Given:
<ul>
  <li>σ = 1.25</li>
  <li>n = 10</li>
  <li>x̄= 40.5</li>
  <li>∝ = 0.05</li>
 </ul>
 
#### What is the P-value for the test in part A?

#### What is the β-error for the text in part B if the true mean life is 42 hours?

#### What sample size would be required to ensure that β does not exceed 0.10 if the true mean is 44 hours?

#### Explain how you could answer the question in part A by calculating an appropriate confidence bound on battery life.


## Question 2

### Brand A gasoline was used in 16 similar automobiles under identical conditions. The corresponding sample of 16 values (miles per gallon) had mean 19.6 and standard deviation 0.4. Under the same conditions, high-power brand B gasoline gave a sample of 16 values with mean 20.2 and standard deviation 0.6. Is the mileage of B significantly better than that of A? Assume normality. Test the hypothesis using both P-value and fixed significance level with α=0.05 approaches (if possible)

